# main: g++ -Wall -g main.o Contestant.o Team.o University.o -o main
#
# main.o: g++ -Wall -g main.cpp Contestant.cpp Contestant.h Team.cpp Team.h University.cpp University.h -c main.o
#
# Contestant.o: g++ -Wall -g Contestant.cpp Contestant.h -c Contestant.o
#
# Team.o: g++ -Wall -g Team.cpp Team.h -c Team.o
#
# University.o: g++ -Wall -g University.cpp University.h -c University.o
main:  main.cpp Contestant.cpp Contestant.h Team.cpp Team.h University.cpp University.h
	g++ -Wall -g main.cpp Contestant.cpp Team.cpp University.cpp -o main
